include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - .dart_tool/**
  errors:
    todo: ignore

linter:
  rules:
    prefer_single_quotes: true
    require_trailing_commas: true
    use_key_in_widget_constructors: true
    prefer_final_fields: true
    prefer_final_locals: true
