include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_return: warning
    dead_code: info
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    - always_declare_return_types
    - avoid_empty_else
    - avoid_print
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_single_quotes
    - sort_child_properties_last
    - use_key_in_widget_constructors
